# Generated by Django 3.0.7 on 2020-07-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0004_userprofile_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
